### ISSUE TITLE
Exception on start (needs investigation)

### ISSUE THREAD

**Issue by jbpratt** [jbpratt/strims-chat-mobile#62]
```
An Observatory debugger and profiler on iPhone Xʀ is available at: http://127.0.0.1:49403/ARqwXtPwLqg=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12:
flutter: '!owner._nodes.containsKey(id)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1439:12)
flutter: #3      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
flutter: #4      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1366:11)
flutter: #5      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1767:5)
flutter: #6      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:869:10)
flutter: #7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3460:13)
flutter: #8      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #9      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
flutter: #10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
flutter: #11     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
flutter: #12     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #13     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3452:16)
flutter: #14     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #15     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #16     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3452:16)
flutter: #17     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #18     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #19     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3452:16)
flutter: #20     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #21     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #22     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3452:16)
flutter: #23     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #24     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
flutter: #25     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #26     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3452:16)
flutter: #27     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #28     Iterable.single (dart:core/iterable.dart:552:13)
flutter: #29     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2406:7)
flutter: #30     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:958:16)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:350:19)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #40     _invoke (dart:ui/hooks.dart:236:10)
flutter: #41     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1439 pos 12: '!owner._nodes.containsKey(id)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart'...
```

**Comment by aliveSurfin** [comment]
rework to visibility instead of null ternary
